export default {
    electrico: [{
        item: '',
        MaterialesElectricos: '',
    }, ],
    obracivil: [{
        item: '',
        MaterialesObracivil: '',
    }, ],
    equipo: [{
        item: '',
        Equipo: '',
    }, ],
    transporte: [{
        item: '',
        Transporte: '',
    }, ],
    manoobra: [{
        item: '',
        ManoObra: '',
    }, ],
    totales: [{
        item: '',
    }, ],

    items: [{
            item: '1.1',
            descripcion: 'Suministro e instalación de Salida de Iluminación, incluye tubería EMT de 3/4" con accesorios, caja Metalica 12x12x5 con tapa, prensa estopa, 1,5 m cable encauchetado 3x14 AWG, circuito en alambre N°12 AWG, conectores de derivación de resorte  y demás',
            unidad: 'UN',
            cantidad: 24.3,
            valorunit: 4.0,
        },
        {
            item: '1.2',
            descripcion: '',
            unidad: '',
            cantidad: '',
            valorunit: '',
        },
        {
            item: '2.1',
            descripcion: '',
            unidad: '',
            cantidad: '',
            valorunit: '',
        },
        {
            item: '2.2',
            descripcion: '',
            unidad: '',
            cantidad: '',
            valorunit: '',
        },
        {
            item: '3.1',
            descripcion: '',
            unidad: '',
            cantidad: '',
            valorunit: '',
        },
        {
            item: '3.2',
            descripcion: '',
            unidad: '',
            cantidad: '',
            valorunit: '',
        },
    ],

    items2: [{
            item: '1.1',
            descripcion: '',
            unidad: '',
            cantidad: '',
            valorunit: '',
        },
        {
            item: '1.2',
            descripcion: '',
            unidad: '',
            cantidad: '',
            valorunit: '',
        },
        {
            item: '2.1',
            descripcion: '',
            unidad: '',
            cantidad: '',
            valorunit: '',
        },
        {
            item: '2.2',
            descripcion: '',
            unidad: '',
            cantidad: '',
            valorunit: '',
        },
        {
            item: '3.1',
            descripcion: '',
            unidad: '',
            cantidad: '',
            valorunit: '',
        },
        {
            item: '3.2',
            descripcion: '',
            unidad: '',
            cantidad: '',
            valorunit: '',
        },
    ],


    items1: [{
            item: '1.1',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 24.3,
            valorunit: 4.0,
        },
        {
            item: '1.2',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 37.2,
            valorunit: 4.3,
        },
        {
            item: '1.3',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 23.2,
            valorunit: 6.0,
        },
        {
            item: '1.4',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 67.3,
            valorunit: 4.3,
        },
        {
            item: '2.1',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 49.0,
            valorunit: 3.9,
        },
        {
            item: '2.2',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 94.0,
            valorunit: 0.0,
        },
        {
            item: '2.3',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 98.0,
            valorunit: 0.0,
        },
        {
            item: '3.1',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 87.8,
            valorunit: 6.5,
        },
        {
            item: '3.2',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 51.8,
            valorunit: 4.9,
        },
        {
            item: '3.3',
            descripcion: 'Suministro, transporte y construcción de ...',
            unidad: 'Un',
            cantidad: 65.8,
            valorunit: 7.0,
        },
    ],

    indirectos: [{
            descripcion: "Administración",
            porcentaje: "10%",
            vrindirecto: "$42345",
        },
        {
            descripcion: "Imprevistos",
            porcentaje: "5%",
            vrindirecto: "$9876",
        },
        {
            descripcion: "Utilidades",
            porcentaje: "7%",
            vrindirecto: "$15645",
        },
    ],

    impuestos: [{
            descripcion: "IVA/Utilidades",
            porcentaje: "19%",
            vrindirecto: "$12345",
        },
        {
            descripcion: "IVA Pleno",
            porcentaje: "19%",
            vrindirecto: "$12345",
        },
    ],
    cotizacion: [{
        cliente: "Consorcio Ingenieria S.A.",
        proyecto: "Casa N° 12 Bosques de Canaria",
        contenido: " Cuadro de cantidades y precios intalaciones",
        fecha: "12/09/2021",
        numero_cot: "CT-001",
        ciudad: "Armenia",
    }]
}